# Generated by GitHub Copilot

"""CRM API routes.

Four endpoints under the ``/crm`` prefix — all read-only (GET).

Route map
---------
GET /crm/                             All customers RM pipeline summary
GET /crm/{customer_id}                Demographics + account metadata + RM info
GET /crm/{customer_id}/interactions   Conversations (filterable) + open tickets
GET /crm/{customer_id}/advisory       Suggestions + compliance flags + alerts
"""

from __future__ import annotations

import logging
from typing import Annotated, Any

from fastapi import APIRouter, HTTPException, Query

from app.errors import DataAccessError
from app.services.crm_tools import CrmTools

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/crm", tags=["CRM"])
_tools = CrmTools()


def _raise_404_if_not_found(exc: DataAccessError, customer_id: str) -> None:
    """Re-raise DataAccessError as HTTP 404 when a customer record is missing."""
    if "No record found" in exc.message:
        raise HTTPException(
            status_code=404,
            detail=f"Customer '{customer_id}' not found in the CRM database.",
        ) from exc
    raise exc


@router.get(
    "/",
    summary="All customers — RM pipeline summary",
    response_description="Lightweight pipeline view for every customer.",
)
def list_customers_summary() -> list[dict[str, Any]]:
    """Return an RM pipeline overview for all customers.

    Merges segment, NPS score, churn risk, last interaction date, pending
    follow-ups, open suggestions, and compliance flags into one record per
    customer. Suitable for RM daily dashboards and retention reviews.

    Returns:
        List of summary dicts (one per customer).
    """
    logger.info("CRM customer summary list requested")
    return _tools.get_all_customers_summary()


@router.get(
    "/{customer_id}",
    summary="Customer full profile",
    response_description="Demographics, account metadata, and RM info merged.",
)
def get_customer_full_profile(customer_id: str) -> dict[str, Any]:
    """Return the complete profile for a single customer.

    Merges three sections into one pre-meeting context response:
    - **customer_profile**: contact details, KYC status, segment, preferred
      communication channel, city/address.
    - **account_metadata**: lifetime value, NPS score, churn risk,
      satisfaction rating, interaction statistics, suggestion acceptance ratio.
    - **relationship_manager**: RM name, employee ID, designation, branch.

    Args:
        customer_id: Customer identifier, e.g. ``CUST-1001``.

    Returns:
        Dict with ``customer_profile``, ``account_metadata``, and
        ``relationship_manager``.

    Raises:
        404: If no CRM record is found for the customer.
    """
    logger.info("Customer full profile requested", extra={"customer_id": customer_id})
    try:
        return _tools.get_customer_full_profile(customer_id)
    except DataAccessError as exc:
        _raise_404_if_not_found(exc, customer_id)


@router.get(
    "/{customer_id}/interactions",
    summary="Interactions — conversations + open service requests",
    response_description="Filtered conversation history and open service tickets.",
)
def get_interactions(
    customer_id: str,
    channel: Annotated[
        str | None,
        Query(description="Filter by channel: phone | email | in_person | video_call | app_chat"),
    ] = None,
    sentiment: Annotated[
        str | None,
        Query(description="Filter by sentiment: positive | neutral | negative"),
    ] = None,
    limit: Annotated[
        int | None,
        Query(ge=1, le=50, description="Return only the most recent N conversations."),
    ] = None,
) -> dict[str, Any]:
    """Return conversation history and open service requests for a customer.

    Merges both interaction data sources into a single response with optional
    filters so callers never need two round-trips:

    - **conversations**: full history, optionally filtered by channel, sentiment,
      or capped to the most recent N records.
    - **open_service_requests**: tickets that are not yet resolved.

    Args:
        customer_id: Customer identifier.
        channel: Optional channel filter — ``phone``, ``email``, ``in_person``,
            ``video_call``, or ``app_chat`` (case-insensitive).
        sentiment: Optional sentiment filter — ``positive``, ``neutral``,
            or ``negative`` (case-insensitive).
        limit: Optional cap on the number of conversations returned (1–50).

    Returns:
        Dict with ``conversations`` and ``open_service_requests``.
    """
    logger.info(
        "Interactions requested",
        extra={
            "customer_id": customer_id,
            "channel": channel,
            "sentiment": sentiment,
            "limit": limit,
        },
    )
    try:
        return _tools.get_interactions(customer_id, channel=channel, sentiment=sentiment, limit=limit)
    except DataAccessError as exc:
        _raise_404_if_not_found(exc, customer_id)


@router.get(
    "/{customer_id}/advisory",
    summary="Advisory view — suggestions, compliance, alerts",
    response_description="All suggestions, pending subset, compliance flags, and alerts.",
)
def get_advisory_view(customer_id: str) -> dict[str, Any]:
    """Return the advisory summary for a customer.

    Merges the three sections an RM checks before each client interaction:

    - **suggestions_provided**: complete history of product recommendations,
      rebalancing, tax optimization, and risk review suggestions — with status
      and outcome details for each.
    - **pending_suggestions**: filtered subset of suggestions still awaiting
      client decision or currently in progress.
    - **compliance_flags**: active KYC, documentation, or regulatory flags
      (empty list for fully compliant customers).
    - **alerts**: plain-text action reminders requiring immediate RM attention.

    Args:
        customer_id: Customer identifier.

    Returns:
        Dict with ``suggestions_provided``, ``pending_suggestions``,
        ``compliance_flags``, and ``alerts``.
    """
    logger.info("Advisory view requested", extra={"customer_id": customer_id})
    try:
        return _tools.get_advisory_view(customer_id)
    except DataAccessError as exc:
        _raise_404_if_not_found(exc, customer_id)
