# Generated by GitHub Copilot

"""Portfolio API routes.

Four endpoints under the ``/portfolio`` prefix — all read-only (GET).

Route map
---------
GET /portfolio/                           All portfolios RM summary
GET /portfolio/{customer_id}              Holdings + asset allocation + P&L
GET /portfolio/{customer_id}/performance  Metrics + sector/geo exposure + events
GET /portfolio/{customer_id}/compliance   LOC + tax summary + alerts
"""

from __future__ import annotations

import logging
from typing import Any

from fastapi import APIRouter, HTTPException

from app.errors import DataAccessError
from app.services.portfolio_tools import PortfolioTools

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/portfolio", tags=["Portfolio"])
_tools = PortfolioTools()


def _raise_404_if_not_found(exc: DataAccessError, customer_id: str) -> None:
    """Re-raise DataAccessError as HTTP 404 when a customer record is missing."""
    if "No record found" in exc.message:
        raise HTTPException(
            status_code=404,
            detail=f"Customer '{customer_id}' not found in the portfolio database.",
        ) from exc
    raise exc


@router.get(
    "/",
    summary="All portfolios — RM summary",
    response_description="Lightweight summary for every customer in the book.",
)
def list_portfolios_summary() -> list[dict[str, Any]]:
    """Return an RM book-of-business overview for all customers.

    Merges account details, portfolio KPIs, and alerts into one lightweight
    record per customer. Designed for relationship manager dashboards.

    Returns:
        List of summary dicts with customer name, AUM, YTD return, alpha,
        RM name, and alerts.
    """
    logger.info("Portfolio summary list requested")
    return _tools.get_all_portfolios_summary()


@router.get(
    "/{customer_id}",
    summary="Portfolio snapshot — holdings, allocation, P&L",
    response_description="Merged holdings, asset allocation, and P&L for one customer.",
)
def get_portfolio_snapshot(customer_id: str) -> dict[str, Any]:
    """Return the holdings snapshot for a single customer.

    Merges account details, customer profile, portfolio summary KPIs, asset
    class allocation, individual instrument holdings, and the full P&L statement
    (realized STCG/LTCG, unrealized gains by asset class, dividends, and
    interest income) into one response.

    Suitable for pre-meeting position reviews and client reporting.

    Args:
        customer_id: Customer identifier, e.g. ``CUST-1001``.

    Returns:
        Dict with ``account_details``, ``customer_profile``,
        ``portfolio_summary``, ``asset_allocation``, ``holdings``, and
        ``pnl_summary``.

    Raises:
        404: If no record is found for the customer.
    """
    logger.info("Portfolio snapshot requested", extra={"customer_id": customer_id})
    try:
        return _tools.get_portfolio_snapshot(customer_id)
    except DataAccessError as exc:
        _raise_404_if_not_found(exc, customer_id)


@router.get(
    "/{customer_id}/performance",
    summary="Performance view — metrics, exposure, events",
    response_description="Returns, risk ratios, sector/geo exposure, and upcoming events.",
)
def get_performance_view(customer_id: str) -> dict[str, Any]:
    """Return the investment performance view for a single customer.

    Merges time-period returns (1M/3M/6M/1Y/3Y/5Y/YTD), benchmark comparison,
    risk-adjusted metrics (alpha, beta, Sharpe, Sortino, max drawdown,
    volatility, information ratio), sector-level portfolio weights, domestic vs
    international geographic breakdown, and the upcoming event calendar
    (maturities, dividends, SIP dates, derivative expiries, reviews).

    Designed for investment committee reviews and IPS compliance checks.

    Args:
        customer_id: Customer identifier.

    Returns:
        Dict with ``performance_metrics``, ``sector_exposure``,
        ``geographic_exposure``, and ``upcoming_events``.
    """
    logger.info("Performance view requested", extra={"customer_id": customer_id})
    try:
        return _tools.get_performance_view(customer_id)
    except DataAccessError as exc:
        _raise_404_if_not_found(exc, customer_id)


@router.get(
    "/{customer_id}/compliance",
    summary="Compliance view — LOC, tax, alerts",
    response_description="Line of credit details, tax summary, and active alerts.",
)
def get_compliance_view(customer_id: str) -> dict[str, Any]:
    """Return the compliance and risk-management view for a single customer.

    Merges the Line of Credit facility (sanctioned/utilized/available amounts,
    interest rate, collateral, LTV, expiry), the current-year tax summary
    (STCG/LTCG amounts, estimated liability, TDS deducted, tax-loss harvesting
    opportunity), and active alert messages that require RM attention.

    Args:
        customer_id: Customer identifier.

    Returns:
        Dict with ``line_of_credit`` (``null`` if none), ``tax_summary``,
        and ``alerts``.
    """
    logger.info("Compliance view requested", extra={"customer_id": customer_id})
    try:
        return _tools.get_compliance_view(customer_id)
    except DataAccessError as exc:
        _raise_404_if_not_found(exc, customer_id)
