# Generated by GitHub Copilot

"""Request and response schemas for the POC API.

Includes Unique Toolkit-aligned types:
  ContentChunk       — referenceable document chunk (mirrors unique_toolkit ContentChunk)
  ToolCallResponse   — structured tool output (mirrors unique_toolkit ToolCallResponse)
  ToolDescription    — LLM-readable tool schema (mirrors LanguageModelToolDescription)
  EvaluationMetricResult — quality-check result (mirrors unique_toolkit EvaluationMetricResult)

Ordering: Unique Toolkit types are defined first so forward-reference resolution
is unambiguous in all Python and Pydantic v2 contexts.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field, field_validator


# ─── Unique Toolkit-aligned types (defined first — used by response schemas) ─


class ContentChunk(BaseModel):
    """Represent a referenceable document chunk from a Tool response.

    Mirrors unique_toolkit ContentChunk — used by ReferenceManager to
    build UI source citations (e.g. [1]↗).
    """

    id: str
    chunk_id: str = "0"
    text: str
    metadata: dict[str, Any] = Field(default_factory=dict)

    @property
    def source_id(self) -> str:
        """Return the ReferenceManager-compatible identifier (id-chunk_id)."""
        return f"{self.id}-{self.chunk_id}"


class ToolCallResponse(BaseModel):
    """Structured output returned by a Tool after execution.

    Mirrors unique_toolkit.agentic.tool_call_response.ToolCallResponse.

    Fields
    ------
    content        — plain text output (used when no citations are needed)
    content_chunks — referenceable chunks processed by ReferenceManager
    debug_info     — captured by DebugInfoManager for developer inspection
    error_message  — non-empty string signals a failed execution to the LLM
    """

    id: str
    name: str
    content: str = ""
    content_chunks: list[ContentChunk] | None = None
    debug_info: dict[str, Any] | None = None
    error_message: str = ""

    @property
    def successful(self) -> bool:
        """Return True when the tool executed without errors."""
        return not bool(self.error_message)


class ToolDescription(BaseModel):
    """LLM-readable tool definition used in the orchestrator planning step.

    Mirrors unique_toolkit LanguageModelToolDescription.
    """

    name: str
    description: str
    parameters: dict[str, Any]


class EvaluationMetricResult(BaseModel):
    """Result of a quality evaluation run.

    Mirrors unique_toolkit EvaluationMetricResult — surfaced to the chat
    UI (PENDING → result) in a full Unique platform deployment.
    """

    name: str
    is_positive: bool
    value: str
    reason: str


# ─── API request / response schemas ──────────────────────────────────────────


class RelationshipManagerRequest(BaseModel):
    """Represent an incoming relationship manager query."""

    customer_id: str = Field(min_length=1, description="Customer identifier used by the sub-agents.")
    question: str = Field(min_length=3, description="Natural language question from the relationship manager.")

    @field_validator("customer_id", "question")
    @classmethod
    def strip_values(cls, value: str) -> str:
        """Normalize string fields before business processing."""
        return value.strip()


class AgentAnswer(BaseModel):
    """Represent an answer generated by one sub-agent."""

    agent_name: Literal["portfolio", "crm"]
    summary: str
    retrieved_context: dict


class RelationshipManagerResponse(BaseModel):
    """Represent the orchestrated result returned to the client."""

    customer_id: str
    question: str
    routing_decision: list[str]
    final_answer: str
    agent_answers: list[AgentAnswer]
    debug_info: dict[str, Any] = Field(default_factory=dict)
    evaluation_results: list[EvaluationMetricResult] = Field(default_factory=list)


class HealthResponse(BaseModel):
    """Represent the service health payload."""

    status: str
    app_name: str
    environment: str
