# Generated by GitHub Copilot

"""Thin adapter around the Unique AI toolkit and SDK completion layer.

Provides a single facade that:
  1. Tries unique_toolkit.language_model.service.LanguageModelService (higher-level)
  2. Falls back to unique_sdk.ChatCompletion.create (documented SDK API)

Both paths are instrumented with structured logging so every call is
visible in the application logs.

References
----------
docs/unique_sdk_ai_completion_advanced_api.md   — ChatCompletion API usage
docs/unique_toolkit_overview_chat_knowledge_events.md — LanguageModelService
"""

from __future__ import annotations

import json
import logging
from typing import Any

from app.errors import UniqueIntegrationError
from app.settings import Settings
from app.services.unique_client import UniqueAIClient

logger = logging.getLogger(__name__)

try:
    from unique_toolkit.language_model.service import LanguageModelService
    logger.debug("unique_toolkit.language_model.service imported successfully")
except ImportError:
    LanguageModelService = None  # type: ignore[assignment,misc]
    logger.info("unique_toolkit not installed — will use unique-sdk ChatCompletion.create directly")


class UniqueToolkit:
    """Single facade for all agentic Unique AI interactions.

    Keeps all Unique SDK / Toolkit boundary crossings behind this class so the
    rest of the application never imports unique_sdk or unique_toolkit directly.
    This mirrors the 'single SDK boundary' principle used in the Unique platform
    documentation.
    """

    def __init__(self, client: UniqueAIClient) -> None:
        """Initialize the toolkit facade with the configured Unique AI client."""
        self.client = client
        self.settings: Settings = client.settings
        logger.debug(
            "UniqueToolkit initialized",
            extra={"model_name": self.settings.unique_model_name},
        )

    def execute(
        self,
        agent_name: str,
        prompt: str,
        context: dict[str, Any],
        question: str,
    ) -> str:
        """Execute a sub-agent completion through Unique Toolkit or SDK.

        Builds OpenAI-style messages per the documented ChatCompletion format,
        then tries unique_toolkit first, falling back to unique_sdk.

        References
        ----------
        docs/unique_sdk_ai_completion_advanced_api.md — ChatCompletion API
        docs/unique_toolkit_overview_chat_knowledge_events.md — LanguageModelService
        """
        logger.info(
            "UniqueToolkit.execute called",
            extra={"agent_name": agent_name, "question_length": len(question)},
        )
        messages = self._build_messages(prompt=prompt, question=question, context=context)

        # Path 1: unique_toolkit LanguageModelService (preferred)
        toolkit_response = self._try_toolkit_completion(messages=messages)
        if toolkit_response:
            logger.info(
                "UniqueToolkit.execute completed via unique_toolkit path",
                extra={"agent_name": agent_name, "response_length": len(toolkit_response)},
            )
            return toolkit_response

        # Path 2: unique_sdk ChatCompletion.create (documented SDK fallback)
        logger.info(
            "UniqueToolkit.execute falling back to unique_sdk path",
            extra={"agent_name": agent_name},
        )
        result = self.client.run_completion(
            agent_name=agent_name,
            messages=messages,
        )
        logger.info(
            "UniqueToolkit.execute completed via unique_sdk path",
            extra={"agent_name": agent_name, "response_length": len(result)},
        )
        return result

    def plan_with_tools(
        self,
        *,
        messages: list[dict[str, Any]],
        tool_definitions: list[dict[str, Any]],
        forced_tool_name: str | None = None,
        allow_tools: bool = True,
    ) -> dict[str, Any]:
        """Run a planning completion that can request function tool calls.

        Used by the orchestrator to decide which tools to invoke in each iteration.
        Passes tool_definitions as OpenAI-style function schemas.

        References
        ----------
        docs/unique_sdk_ai_completion_advanced_api.md — tools / tool_choice format
        docs/unique_toolkit_agentic_framework_core.md — orchestrator planning step
        """
        tool_choice: dict[str, Any] | str | None = None
        tools: list[dict[str, Any]] | None = None

        if allow_tools and tool_definitions:
            tools = tool_definitions
            if forced_tool_name:
                tool_choice = {
                    "type": "function",
                    "function": {"name": forced_tool_name},
                }
            logger.info(
                "UniqueToolkit.plan_with_tools: calling LLM with tools enabled",
                extra={
                    "tool_count": len(tool_definitions),
                    "forced_tool": forced_tool_name,
                    "message_count": len(messages),
                },
            )
        else:
            logger.info(
                "UniqueToolkit.plan_with_tools: calling LLM with tools disabled (final-answer mode)",
                extra={"message_count": len(messages)},
            )

        response = self.client.create_completion(
            messages=messages,
            tools=tools,
            tool_choice=tool_choice,
            temperature=0.2,
        )

        content = self.client._extract_completion_text(response)
        tool_calls = self.client.extract_tool_calls(response)

        logger.info(
            "UniqueToolkit.plan_with_tools completed",
            extra={
                "has_content": bool(content),
                "tool_call_count": len(tool_calls),
                "content_length": len(content or ""),
            },
        )

        return {
            "content": content,
            "tool_calls": tool_calls,
            "raw": response,
        }

    def finalize_answer(self, *, messages: list[dict[str, Any]]) -> str:
        """Generate a final answer with tools disabled for predictable loop termination.

        Mirrors the Unique orchestrator last-iteration no-tools mode.
        """
        logger.info(
            "UniqueToolkit.finalize_answer: generating final answer (tools disabled)",
            extra={"message_count": len(messages)},
        )
        response = self.client.create_completion(
            messages=messages,
            tools=None,
            tool_choice=None,
            temperature=0.1,
        )
        answer = self.client._extract_completion_text(response)
        if answer:
            logger.info(
                "UniqueToolkit.finalize_answer completed",
                extra={"answer_length": len(answer)},
            )
            return answer
        logger.warning("UniqueToolkit.finalize_answer: empty response from LLM")
        return "I could not generate a final answer from the available context."

    # ── Private helpers ───────────────────────────────────────────────────────

    def _build_messages(
        self, prompt: str, question: str, context: dict[str, Any]
    ) -> list[dict[str, str]]:
        """Build OpenAI-style messages compatible with Unique SDK ChatCompletion.

        References
        ----------
        docs/unique_sdk_ai_completion_advanced_api.md — Message Format section
        """
        context_json = json.dumps(context, ensure_ascii=True, indent=2, sort_keys=True)
        return [
            {"role": "system", "content": prompt},
            {
                "role": "user",
                "content": (
                    "Use the retrieved relationship-manager context to answer the question. "
                    "Do not invent facts beyond the provided context.\n\n"
                    f"Question: {question}\n\n"
                    f"Retrieved Context:\n{context_json}"
                ),
            },
        ]

    def _try_toolkit_completion(self, messages: list[dict[str, str]]) -> str:
        """Attempt a standalone completion through the documented Unique Toolkit service.

        Returns an empty string if unique_toolkit is not installed or the call fails,
        signalling the caller to fall back to the SDK path.
        """
        if LanguageModelService is None:
            logger.debug("_try_toolkit_completion: unique_toolkit not available; skipping")
            return ""

        try:
            service = self._build_language_model_service()
            complete = getattr(service, "complete", None)
            if complete is None or not callable(complete):
                raise UniqueIntegrationError(
                    "unique_toolkit LanguageModelService.complete is not callable as documented.",
                    {"package": "unique_toolkit"},
                )

            payload = self.client._filter_supported_arguments(
                complete,
                {
                    "messages": messages,
                    "model_name": self.settings.unique_model_name,
                    "temperature": 0.2,
                },
            )
            logger.debug(
                "_try_toolkit_completion: calling LanguageModelService.complete",
                extra={"payload_keys": list(payload.keys())},
            )
            result = complete(**payload)
            normalized = self.client._extract_completion_text(result)
            if normalized:
                logger.debug(
                    "_try_toolkit_completion: success",
                    extra={"response_length": len(normalized)},
                )
                return normalized
            logger.warning("_try_toolkit_completion: empty response; falling back to unique-sdk")
            return ""
        except UniqueIntegrationError:
            raise
        except Exception:
            logger.exception("_try_toolkit_completion: exception; falling back to unique-sdk")
            return ""

    def _build_language_model_service(self) -> Any:
        """Instantiate LanguageModelService with auth IDs from runtime settings."""
        try:
            return LanguageModelService(
                company_id=self.settings.unique_auth_company_id,
                user_id=self.settings.unique_auth_user_id,
            )
        except Exception as exc:
            raise UniqueIntegrationError(
                "Unable to initialize LanguageModelService from unique_toolkit.",
                {"package": "unique_toolkit"},
            ) from exc
